obj-$(CONFIG_MIGT)			+= migt.o

obj-$(CONFIG_MIGT_ENERGY_MODEL)		+= migt_energy_model.o
migt_energy_model-y := cpu_energy_dt.o cpu_pcost.o gpu_pcost.o

obj-$(CONFIG_MILLET)			+= millet.o
millet-y := millet_core.o millet_pkg.o millet_hs.o
