obj-$(CONFIG_MIGT)			+= migt.o
obj-$(CONFIG_MILLET)			+= millet_core.o
obj-$(CONFIG_MILLET)			+= millet_pkg.o
obj-$(CONFIG_MILLET)			+= millet_hs.o
obj-$(CONFIG_MIGT_ENERGY_MODEL)		+= cpu_energy_dt.o
obj-$(CONFIG_MIGT_ENERGY_MODEL) 	+= cpu_pcost.o
obj-$(CONFIG_MIGT_ENERGY_MODEL) 	+= gpu_pcost.o
